name: Flutter CI

on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop
      - main

jobs:
  build-and-release:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - uses: actions/setup-java@v3
    #   with:
    #     distribution: 'zulu'
    #     java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
        flutter-version: '3.24.0'

    - name: Install dependencies
      run: flutter pub get
    
    # Generate code (Freezed, Riverpod, etc.)
    - name: Generate code
      run: flutter pub run build_runner build --delete-conflicting-outputs
    
    - name: Build Android APK
      run: flutter build apk --release --split-per-abi

    # - name: Build APK
    #   if: github.ref == 'refs/heads/develop'
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "build/app/outputs/apk/release/*"
    #     tag: v1.0.${{ github.run_number }}
    #     token: ${{ secrets.TOKEN }}

    - name: Push to Releases
      if: github.ref == 'refs/heads/main'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*"
        tag: v1.0.${{ github.run_number }}
        token: ${{ secrets.TOKEN }}


    #- name: Run tests
    #  run: flutter test

    #- name: Build APK
    #  run: flutter build apk --release

    #- name: Upload APK
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: flutter-apk
    #    path: build/app/outputs/flutter-apk/To-do.apk
